server:
  port: 9411

spring:
  application:
    name: ms-zipkin-server
#  rabbitmq:
#    host: ${RABBIT_HOST:localhost}
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    schema: classpath:/mysql.sql
    url: jdbc:mysql://localhost:3306/baocy
    username: root
    password: 123456
# Switch this on to create the schema on startup:
    initialize: true
    continueOnError: true
  sleuth:
    enabled: false
zipkin:
  storage:
    type: mysql